M48
; #@! TF.GenerationSoftware,LibrePCB,LibrePCB,1.1.0
; #@! TF.CreationDate,2024-09-08T17:15:58
; #@! TF.ProjectId,flasher,f4b07f79-14a2-4070-9d7d-1f686dcb10c4,v1
; #@! TF.Part,Single
; #@! TF.SameCoordinates
; #@! TF.FileFunction,NonPlated,1,13,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,MechanicalDrill
T1C5.0
%
G90
G05
M71
T1
X-41.775Y36.835
X41.57Y-36.825
X41.57Y36.835
X-41.775Y-36.825
T0
M30
